apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chartmuseum
    release: chartmuseum
  name: chartmuseum
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: openebs-hostpath-retain
