replicas: 1
minimumMasterNodes: 1

# Allows you to add any config files in /usr/share/elasticsearch/config/
# such as elasticsearch.yml and log4j2.properties
esConfig:
  elasticsearch.yml: |
    cluster.name: "homeserver"
    network.host: 0.0.0.0
    xpack.monitoring.collection.enabled: true
  #  log4j2.properties: |
  #    key = value

persistence:
  enabled: true

volumeClaimTemplate:
  storageClassName: openebs-hostpath-retain
  resources:
    requests:
      storage: 5Gi
