apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: docker-registry
    chart: docker-registry-1.8.3
    heritage: Tiller
    release: docker-registry
  name: docker-registry
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: openebs-hostpath-retain
