apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq-nodeports
spec:
  type: NodePort
  ports:
  - name: mgmt
    nodePort: 31673
    port: 15672
    protocol: TCP
    targetPort: stats
    #  - name: amqp
    #    nodePort: 31672
    #    port: 5672
    #    protocol: TCP
    #    targetPort: amqp
  - name: mqtt
    nodePort: 31883
    port: 1883
    protocol: TCP
    targetPort: mqtt
  - name: mqtt-ssl
    nodePort: 31884
    port: 8883
    protocol: TCP
    targetPort: mqtt-ssl
  selector:
    app.kubernetes.io/instance: rabbitmq
    app.kubernetes.io/name: rabbitmq
